# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Code to Cloud CI

on:
  pull_request:
    branches: [ master, reusable-workflow-test ]
  push:
    branches: [ reusable-workflow-test ]

jobs:
  APPSCAN:
    # Consume reusable AppSec workflow
    uses: octodemo/reusable-workflows/.github/workflows/appsec_scan.yml@main
    with:
      core_language: "javascript"
      deploy_url: "https://www.yahoo.com"
  CI:  
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
    
      with:
        node-version: ${{ matrix.node-version }}
    
    - run: npm install
    - run: npm test
